[package]
name = "ssm-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
russh = "0.40"
russh-keys = "0.40"
async-trait = "0.1"
uuid = { version = "1", features = ["v4"] }
log = "0.4"
env_logger = "0.11"
anyhow = "1.0.100"
